spring:
  application:
    name: SiWorkflow
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.55.11:3306/siworkflow?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true

server:
  port: 9000

logging:
  file: siworkflow.log