spring:
  application:
    name: SiWorkflow
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xgdash?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ''
  jpa:
    show-sql: true

server:
  port: 9000